apiVersion: v1
kind: Pod
metadata:
  name: configmap-checker
spec:
  containers:
  - name: configmap-checker-container
    image: busybox
    command: ["/bin/sh", "-ec", "while true; do cat /etc/config/port; sleep 3600; done"]
    readinessProbe:
      exec:
        command:
        - cat
        - /etc/config/port
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      exec:
        command:
        - cat
        - /etc/config/port
      initialDelaySeconds: 10
      periodSeconds: 10
    startupProbe:
      exec:
        command:
        - cat
        - /etc/config/port
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 30
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: port-config